/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StreetmapRouteImport } from './routes/streetmap'
import { Route as LinksRouteImport } from './routes/links'
import { Route as InfoRouteImport } from './routes/info'
import { Route as FlagdaysRouteImport } from './routes/flagdays'
import { Route as AreamapRouteImport } from './routes/areamap'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtiklerIndexRouteImport } from './routes/artikler/index'
import { Route as ArtiklerSlugRouteImport } from './routes/artikler/$slug'

const StreetmapRoute = StreetmapRouteImport.update({
  id: '/streetmap',
  path: '/streetmap',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoRoute = InfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => rootRouteImport,
} as any)
const FlagdaysRoute = FlagdaysRouteImport.update({
  id: '/flagdays',
  path: '/flagdays',
  getParentRoute: () => rootRouteImport,
} as any)
const AreamapRoute = AreamapRouteImport.update({
  id: '/areamap',
  path: '/areamap',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtiklerIndexRoute = ArtiklerIndexRouteImport.update({
  id: '/artikler/',
  path: '/artikler/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtiklerSlugRoute = ArtiklerSlugRouteImport.update({
  id: '/artikler/$slug',
  path: '/artikler/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/areamap': typeof AreamapRoute
  '/flagdays': typeof FlagdaysRoute
  '/info': typeof InfoRoute
  '/links': typeof LinksRoute
  '/streetmap': typeof StreetmapRoute
  '/artikler/$slug': typeof ArtiklerSlugRoute
  '/artikler/': typeof ArtiklerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/areamap': typeof AreamapRoute
  '/flagdays': typeof FlagdaysRoute
  '/info': typeof InfoRoute
  '/links': typeof LinksRoute
  '/streetmap': typeof StreetmapRoute
  '/artikler/$slug': typeof ArtiklerSlugRoute
  '/artikler': typeof ArtiklerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/areamap': typeof AreamapRoute
  '/flagdays': typeof FlagdaysRoute
  '/info': typeof InfoRoute
  '/links': typeof LinksRoute
  '/streetmap': typeof StreetmapRoute
  '/artikler/$slug': typeof ArtiklerSlugRoute
  '/artikler/': typeof ArtiklerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/areamap'
    | '/flagdays'
    | '/info'
    | '/links'
    | '/streetmap'
    | '/artikler/$slug'
    | '/artikler/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/areamap'
    | '/flagdays'
    | '/info'
    | '/links'
    | '/streetmap'
    | '/artikler/$slug'
    | '/artikler'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/areamap'
    | '/flagdays'
    | '/info'
    | '/links'
    | '/streetmap'
    | '/artikler/$slug'
    | '/artikler/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AreamapRoute: typeof AreamapRoute
  FlagdaysRoute: typeof FlagdaysRoute
  InfoRoute: typeof InfoRoute
  LinksRoute: typeof LinksRoute
  StreetmapRoute: typeof StreetmapRoute
  ArtiklerSlugRoute: typeof ArtiklerSlugRoute
  ArtiklerIndexRoute: typeof ArtiklerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/streetmap': {
      id: '/streetmap'
      path: '/streetmap'
      fullPath: '/streetmap'
      preLoaderRoute: typeof StreetmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info': {
      id: '/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof InfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flagdays': {
      id: '/flagdays'
      path: '/flagdays'
      fullPath: '/flagdays'
      preLoaderRoute: typeof FlagdaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areamap': {
      id: '/areamap'
      path: '/areamap'
      fullPath: '/areamap'
      preLoaderRoute: typeof AreamapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikler/': {
      id: '/artikler/'
      path: '/artikler'
      fullPath: '/artikler/'
      preLoaderRoute: typeof ArtiklerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikler/$slug': {
      id: '/artikler/$slug'
      path: '/artikler/$slug'
      fullPath: '/artikler/$slug'
      preLoaderRoute: typeof ArtiklerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AreamapRoute: AreamapRoute,
  FlagdaysRoute: FlagdaysRoute,
  InfoRoute: InfoRoute,
  LinksRoute: LinksRoute,
  StreetmapRoute: StreetmapRoute,
  ArtiklerSlugRoute: ArtiklerSlugRoute,
  ArtiklerIndexRoute: ArtiklerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
